- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete deployment --all
     - name: delete old service
       command: kubectl delete svc --all
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/project/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/project/Service.yml
